---
services:
  dind:
    image: docker:24-dind
    command: ["dockerd", "-H", "tcp://0.0.0.0:2375", "--tls=false", "--storage-driver=overlay2"]
    restart: always
    privileged: true
    expose:
      - "2375"
    volumes:
      - "shared-tmp:/tmp"
    environment:
      - DOCKER_TLS_CERTDIR # intentionally blank to optimize runtime
  redis:
    image: redis:6
    expose:
      - "6379"
  postgres:
    image: "postgres:16"
    # this makes postgres log queries
    # command: ["postgres", "-c", "log_statement=all"]
    volumes:
      - "pgdata:/var/lib/postgresql/data"
    expose:
      - "5432"
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=capi
      - POSTGRES_DB=capi
  capi_job_status:
    build:
      context: .
    tty: true
    restart: always
    configs:
      - source: capi
        target: /etc/capi/config.yaml
    environment:
      - MODE=monitor
      - AIXCC_REDIS_HOST=redis
      - AIXCC_WORKER_HEALTH_CHECK_INTERVAL=30
  capi:
    build:
      context: .
    tty: true
    restart: always
    ports:
      - "8082:8080"
    volumes:
      - "shared-tmp:/tmp"
      - "./capi_logs:/var/log/capi"
      - "./cp_root:/cp_root"
    configs:
      - source: capi
        target: /etc/capi/config.yaml
    environment:
      - WEB_CONCURRENCY=$WEB_CONCURRENCY
    env_file:
      - path: ./base.env
        required: true
      - path: ./env
        required: true
  capi_worker:
    build:
      context: .
    tty: true
    restart: always
    volumes:
      - "shared-tmp:/tmp"
      - "./capi_logs:/var/log/capi"
      - "./cp_root:/cp_root"
    configs:
      - source: capi
        target: /etc/capi/config.yaml
    environment:
      - MODE=worker
      - WEB_CONCURRENCY=$WEB_CONCURRENCY
    env_file:
      - path: ./base.env
        required: true
      - path: ./env
        required: true
  loadtest:
    profiles:
      - loadtest
    build:
      context: loadtest
      dockerfile: Dockerfile
    command:
      - run
      - script.js
      - --verbose
    environment:
      - AIXCC_API_HOSTNAME=http://capi:8080
    depends_on:
      capi:
        condition: service_healthy
volumes:
  shared-tmp:
  pgdata:
configs:
  capi:
    file: ./standard_config.yaml
